department-of-veterans-affairs/health-apis-community-care-eligibility

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV1ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-13
Add facilities that meet access standards to community-care-eligibility response
> CCE-13 add facilities that meet access standards to response

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV1ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/API-1181
Added in tests for Facility Transformer
> Add in tests to enhance code coverage

- api-architecture.md
Initial creation of an API Architecture Markdown document for the **Community Care Eligibility API**.  The purpose of this document is to show the interactions between the public-facing Community Care Eligibility API and upstream consumers and downstream systems and act as a talking point.
> Created API Architecture Markdown Document

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Exceptions.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClient.java
https://vasdvp.atlassian.net/browse/API-1206
> API-1026 Improve error message when E&E unavailable

- README.md
- developer.md
https://vasdvp.atlassian.net/browse/CCE-18
> CCE-18 Additional documentation

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Exceptions.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/WebExceptionHandler.java
https://vasdvp.atlassian.net/browse/CCE-30
Modified to match reflect removal of Exception from Queen Elizabeth.
> Removed catch for 'UnknownIdentityInSearchParameter' Exception

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
https://vasdvp.atlassian.net/browse/CCE-34
Path clean-up goodness.
> Remove 'api' from path

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Exceptions.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestBingMapsClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-36
Exceptions are now more descriptive of what went wrong and will alert as to which service is causing the issue.
> Added in exceptions around Facilities, Bing, and EE calls

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/client/RestFacilitiesClientTest.java
https://vasdvp.atlassian.net/browse/CCE-78
> CCE-78 RestFacilitiesClient handle addresses with spaces

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-80
Moving the version information down to the app controller level from the ingress level allowing for greater flexibility in releases (similar to earlier Mock-EE changes)
> Added version portion of path to controller instead of ingress

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/client/RestFacilitiesClientTest.java
Removed post Facilities call filtering and added serviceType to facilities API call. 
Code Coverage dropped 1% due to drop in total lines of code.
> removed post call filtering and added service to Facilities call

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Application.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SteelThreadSystemCheck.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SteelThreadSystemCheckLedger.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SteelThreadSystemCheckLedgerImpl.java
- community-care-eligibility/src/main/resources/application.properties
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/SteelThreadSystemCheckTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/client/SteelThreadSystemCheckLedgerImplTest.java
JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-96
The steel thread health check addition is converted to a scheduled task running every 30 seconds.
> Added scheduled task functionality to health check

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-93
> CCE-93 Add website and rename address to physicalAddress.

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HomeController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HomeControllerV0.java
Updated root path for swagger to be 'v0/eligibility'
This PR will require a follow up change on the CCE kong route.
> changed root path for swagger

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-72
Short circuits added based off EE and /nearby responses
> Updated to short circtuit calls and responses.

- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClient.java
https://vasdvp.atlassian.net/browse/CCE-104
Merge after https://github.com/department-of-veterans-affairs/health-apis-eligibility-and-enrollment-client/pull/13
> CCE-104 Updated hand-of-queen-elizabeth with better authentication error messages

- community-care-eligibility/src/main/resources/application.properties
JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-107
Updated health check frequency to every 5 minutes.
If in the future we want to have different environments have different health check frequencies, the DU will need to be updated to include this value and each environment conf set their respective value.
> Updated health check frequency to every 5 minutes

- README.md
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-111
Quick update to the README and correction of the longitude mapping
> Updated sample in readme and corrected 'longitude' mapping

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/ErrorResponse.java
https://vasdvp.atlassian.net/browse/CCE-113
> CCE-113 Avoid System.currentTimeMillis() for Fortify

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/main/resources/application.properties
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- configuration.md
https://vasdvp.atlassian.net/browse/CCE-109
Removed wait times
Removed Access Standard Check as the Facilities call already returns facilities meeting drive time. (Will add in wait time at a later time once we have a source for live data.)
> Remove wait time and update list of services to search by

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
https://vasdvp.atlassian.net/browse/CCE-118
> CCE-118 NullPointerException on missing address

- Jenkinsfile
- community-care-eligibility-api/pom.xml
- community-care-eligibility/pom.xml
- pom.xml
https://vasdvp.atlassian.net/browse/CCE-125
Don't merge yet, depends on https://github.com/department-of-veterans-affairs/health-apis-eligibility-and-enrollment-client/pull/23
> CCE-125 java 12 upgrade

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Transformers.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClientTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestSoapEligibilityAndEnrollmentClientTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/SteelThreadSystemCheckLedgerImplTest.java
https://vasdvp.atlassian.net/browse/CCE-143
```
2019-09-24 10:42:28.715  INFO 17828 --- [nio-8090-exec-2] .CommunityCareEligibilityV0ApiController : ENTER B942EB 1 search [helloworld, 260, primarycare]
2019-09-24 10:42:28.770  INFO 17828 --- [nio-8090-exec-2] .CommunityCareEligibilityV0ApiController : sessionId=helloworld, patient=260, serviceType=primarycare
2019-09-24 10:42:29.602  INFO 17828 --- [nio-8090-exec-2] g.v.a.h.a.c.SecureRestTemplateConfig     : GET https://api.va.gov/services/va_facilities/v1/nearby?state=NC&city=Raleigh&street_address=694%20Summerhouse%20St.&zip=27601-0400&drive_time=30&type=health&services%5B%5D=PrimaryCare&page=1&per_page=500
2019-09-24 10:42:31.231  INFO 17828 --- [nio-8090-exec-2] g.v.a.h.a.c.SecureRestTemplateConfig     : Response from GET …
```
> CCE-143 Log X-VA-SESSIONID header

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/secure/RapidBoard.jspa?rapidView=115&modal=detail&selectedIssue=CCE-126
Handled new Mobile and Active fields coming from Facilities API.
> Added in new fields and updated tests

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/CCE-158
> CCE-158 Use mapped service-type for validating extended drive-radius

- community-care-eligibility-api/pom.xml
- community-care-eligibility/pom.xml
- pom.xml
https://vasdvp.atlassian.net/browse/SSS-1
> Update CCE to Spring 2.2.0

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
https://vasdvp.atlassian.net/browse/SSS-45
> Community Care: Add Security and SecuritySchemes

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClientTest.java
https://vasdvp.atlassian.net/browse/SSS-52
> Reverted facility v1/nearby to v0/nearby

- .gitignore
- community-care-eligibility/src/main/docker/entrypoint.sh
https://vasdvp.atlassian.net/browse/SSS-58
> SSS-58 Remove regression test for required service-type

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaNearbyFacilitiesResponse.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClientTest.java
https://vasdvp.atlassian.net/secure/RapidBoard.jspa?rapidView=129&view=planning&selectedIssue=SSS-22
> Added in pared-down facilities calls and updated tests

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
https://vasdvp.atlassian.net/browse/SSS-67
Added country to mapping to support international addresses added in https://github.com/department-of-veterans-affairs/health-apis-mock-eligibility-and-enrollment/pull/29
> SSS-67 Added country to address

- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/SSS-7
> SSS-7 Add VAOS service-types and make service-type required

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClient.java
https://vasdvp.atlassian.net/browse/SSS-78
> SSS-78 Side-by-side E&E client refinements

- community-care-eligibility/src/main/docker/entrypoint.sh
https://vasdvp.atlassian.net/browse/SSS-80
> SSS-80 Clean up duplicate smoke and regression tests

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/SSS-116
Fix the same double-spacing bug pointed out on https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/458
> SSS-116 Double-spacing

- community-care-eligibility-api/pom.xml
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/ErrorResponse.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/swaggerexamples/InjectSwaggerExamplesTest.java
- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/EeSummaryPortSupplier.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HomeControllerV0.java
- pom.xml
https://vasdvp.atlassian.net/browse/SHANK-270
Drop SNAPSHOTs after https://github.com/department-of-veterans-affairs/health-apis-parent/pull/49 merges
> SHANK-270 upgrade parent

- CODEOWNERS
- community-care-eligibility/src/main/docker/Dockerfile
Updated Dockerfile to inherit from vasdvp/health-apis-centos:7
> Support VA Certs

- community-care-eligibility-api/pom.xml
- community-care-eligibility/pom.xml
- pom.xml
https://vasdvp.atlassian.net/browse/SHANK-308
> SHANK-308 Upgrade to 6.0 parent with Error Prone

- community-care-eligibility/src/main/docker/Dockerfile
Upgrade CCE to use the new test image base
> new docker base for test image

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Exceptions.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilityTransformer.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/WebExceptionHandler.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/ApplicationTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vasdvp.atlassian.net/browse/SHANK-336
> Shank 336 remove geocoding exception

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HealthController.java
https://vajira.max.gov/browse/API-987
> API-1074 Add v0 to health-check

- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponseTest.java
- community-care-eligibility-api/src/test/java/gov/va/api/health/communitycareeligibility/api/RoundTrip.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/ApplicationTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/HealthControllerTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/HomeControllerV0Test.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClientTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClientTest.java
https://vajira.max.gov/browse/API-1273
> API-1273 JUnit 5

- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/OpenApiIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/Requestor.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/SearchIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/SearchValidationIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/TokenIT.java
https://vajira.max.gov/browse/API-264
> API-1297 Bad IT paths

- Jenkinsfile
- community-care-eligibility-api/pom.xml
- community-care-eligibility-mock-services/pom.xml
- community-care-eligibility-tests/pom.xml
- community-care-eligibility-tests/src/main/docker/Dockerfile
- community-care-eligibility/pom.xml
- developer.md
- pom.xml
Updated build files for Java 14 update.
> Java 14 Update CCE

- community-care-eligibility-api/pom.xml
- community-care-eligibility-mock-services/pom.xml
- community-care-eligibility-tests/pom.xml
- community-care-eligibility/pom.xml
- pom.xml
https://vajira.max.gov/browse/API-1602
Updated versions to 7.0.2
> CCE: Upgrade to 7.0.2 parent

- CODEOWNERS
- Jenkinsfile
- README.md
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vajira.max.gov/browse/API-1312
Api 1312 partial success status codes and documentation updated.
> CCE: Partial success status codes and documentation

- README.md
- developer.md
https://vajira.max.gov/browse/API-1660
> API-1660 Developer documentation clean-up

- community-care-eligibility-mock-services/src/main/resources/application.properties
- community-care-eligibility-tests/pom.xml
https://vajira.max.gov/browse/API-1652
> Change default port for community-care-eligibility-mock-service

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerErrorResponse.java
- community-care-eligibility-tests/pom.xml
- community-care-eligibility-tests/src/main/java/gov/va/api/health/communitycareeligibility/tests/SystemDefinitions.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/AdvancedSearchIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/BasicSearchIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/Requestor.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/TokenIT.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HomeControllerV0.java
https://vajira.max.gov/browse/API-1679
> API-1679 sentinel environment assumptions

- community-care-eligibility/src/main/resources/application.properties
https://vajira.max.gov/browse/API-1779
SecureRestTemplateConfig=OFF added
> CCE: Disable SecureRestTemplateConfig logging

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
https://vajira.max.gov/browse/API-2239
> Api 2239 resolve internal swagger errors

- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/AdvancedSearchIT.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vajira.max.gov/browse/API-5367
> CCE now always returns ineligible when service type request is Primary Care

- community-care-eligibility-mock-services/src/main/java/gov/va/api/health/communitycareeligibilitymockservices/MockServices.java
- community-care-eligibility-mock-services/src/main/resources/pcmm-multiple-pact-data-status-active.xml
- community-care-eligibility-mock-services/src/main/resources/pcmm-no-pact-data.xml
- community-care-eligibility-mock-services/src/main/resources/pcmm-single-pact-data-status-pending.xml
Set up mock endpoints for PCMM data with three different example returns.
https://vajira.max.gov/browse/API-5306
> CCE: Create mock PCMM interface

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
https://vajira.max.gov/browse/API-5307
> Updated to stub out pcmm and nearby facility calls on different threads.

- README.md
- community-care-eligibility-api/pom.xml
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/PcmmResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility-mock-services/src/main/java/gov/va/api/health/communitycareeligibilitymockservices/MockServices.java
- community-care-eligibility-mock-services/src/main/resources/pcmm-multiple-pact-data-status-active.xml
- community-care-eligibility-mock-services/src/main/resources/pcmm-single-pact-data-status-pending.xml
- community-care-eligibility-tests/pom.xml
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/AdvancedSearchIT.java
- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/SearchValidationIT.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Exceptions.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/PcmmClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestPcmmClient.java
- community-care-eligibility/src/main/resources/application.properties
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/RestPcmmClientTest.java
https://vajira.max.gov/browse/API-5309
> Api 5309 pcmm request async thread

- community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/AdvancedSearchIT.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vajira.max.gov/browse/API-5310
> Api 5310 merge pcmm and nearby task results

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HealthController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/HealthControllerTest.java
https://vajira.max.gov/browse/API-5489
> Added PCMM health monitoring

- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/test/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityTest.java
https://vajira.max.gov/browse/API-5568
Updated to reduce nearby call to facilities to one.
> CCE: Update /nearby call logic 

- .mvn/jvm.config
- Jenkinsfile
- community-care-eligibility-api/pom.xml
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/ErrorResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerCommunityCareEligibilityResponse.java
- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/swaggerexamples/SwaggerErrorResponse.java
- community-care-eligibility-mock-services/pom.xml
- community-care-eligibility-mock-services/src/main/java/gov/va/api/health/communitycareeligibilitymockservices/MockServicesApplication.java
- community-care-eligibility-tests/pom.xml
- community-care-eligibility/pom.xml
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/Application.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/EeSummaryPortSupplier.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/EligibilityAndEnrollmentClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/FacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HealthController.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/HomeControllerV0.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/RestFacilitiesClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/SoapEligibilityAndEnrollmentClient.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaFacilitiesResponse.java
- community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/VaNearbyFacilitiesResponse.java
- pom.xml
https://vajira.max.gov/browse/API-7665
> Api 7665 cce java 16 upgrade

- community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/CommunityCareEligibilityService.java
We are adding ExampleObjects to the Parameters.
> Adding ExampleObjects to the Parameters
